import uuid
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, List
from sqlalchemy import String, Text, ForeignKey, DateTime, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base

if TYPE_CHECKING:
    from app.models.patient import Patient


class AIInsight(Base):
    """
    Caregiver AI Insights Record.
    Stores structured, non-diagnostic activity summaries, observations, and recommendations
    generated by Gemini AI or the deterministic fallback engine.
    """
    __tablename__ = "ai_insights"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True,
    )
    patient_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("patients.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    positive_observations: Mapped[Any] = mapped_column(JSON, default=list, nullable=False)
    areas_to_watch: Mapped[Any] = mapped_column(JSON, default=list, nullable=False)
    activity_observations: Mapped[Any] = mapped_column(JSON, default=list, nullable=False)
    suggested_actions: Mapped[Any] = mapped_column(JSON, default=list, nullable=False)
    confidence: Mapped[str] = mapped_column(String(32), default="moderate", nullable=False)
    model: Mapped[str] = mapped_column(String(64), default="gemini-2.5-flash", nullable=False)
    source_metrics_version: Mapped[str] = mapped_column(String(32), default="v1.0", nullable=False)
    raw_metrics: Mapped[Any] = mapped_column(JSON, default=dict, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        nullable=False,
        index=True,
    )

    # Relationships
    patient: Mapped["Patient"] = relationship("Patient", back_populates="ai_insights")
