/**
 * Centralized Demo Fallback Architecture
 * Separates demo/prototype data from real backend API calls.
 * Ensures the prototype stays fully populated and visually complete,
 * while preventing fake demo IDs (e.g., patient-001, med-1, fam-1, apt-1)
 * from ever reaching backend endpoints.
 */

import {
  PatientProfile,
  CaretakerProfile,
  Medication,
  FamilyMember,
  Appointment,
  CognitiveMetrics,
  GameScoreResult,
  AlertItem,
  FamilyStory,
  HydrationSettings,
  GameMetadata,
} from '../types';

import {
  INITIAL_PATIENT,
  DEMO_PATIENTS,
  INITIAL_CARETAKER,
  INITIAL_MEDICATIONS,
  INITIAL_FAMILY_MEMBERS,
  INITIAL_APPOINTMENTS,
  INITIAL_COGNITIVE_METRICS,
  DEMO_COGNITIVE_METRICS,
  INITIAL_GAME_HISTORY,
  DEMO_PATIENT_GAME_HISTORY,
  INITIAL_AI_INSIGHTS,
  WEEKLY_ANALYTICS_DATA,
  INITIAL_ALERTS,
  INITIAL_STORIES,
  INITIAL_HYDRATION_SETTINGS,
  CORE_GAMES,
  DEMO_DATA_DISCLAIMER,
} from './mockData';

/**
 * Custom error thrown when a demo entity ID is accidentally passed to an API service.
 * Prevents unnecessary network calls and avoids 404 responses from backend.
 */
export class DemoModeApiError extends Error {
  public readonly isDemoBlocked = true;

  constructor(message: string = 'Network request blocked for demo entity ID') {
    super(message);
    this.name = 'DemoModeApiError';
    Object.setPrototypeOf(this, DemoModeApiError.prototype);
  }
}

/**
 * Standard UUID v4/v1 regex (case-insensitive)
 */
const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Detects whether an ID is a known demo or simulated entity ID.
 * Examples: 'patient-001', 'patient-002', 'med-1', 'fam-1', 'apt-1', 'alt-1', 'story-1', 'ai-1', 'caretaker-001', 'demo-...'
 */
export function isDemoId(id?: string | null): boolean {
  if (!id || typeof id !== 'string') return true;
  const trimmed = id.trim();
  if (!trimmed) return true;

  return (
    trimmed === 'patient-001' ||
    trimmed === 'patient-002' ||
    trimmed === 'caretaker-001' ||
    /^patient-\d+/i.test(trimmed) ||
    /^caretaker-\d+/i.test(trimmed) ||
    /^med-\d+/i.test(trimmed) ||
    /^fam-\d+/i.test(trimmed) ||
    /^apt-\d+/i.test(trimmed) ||
    /^alt-\d+/i.test(trimmed) ||
    /^story-\d+/i.test(trimmed) ||
    /^ai-\d+/i.test(trimmed) ||
    /^demo-/i.test(trimmed)
  );
}

/**
 * Determines whether a patient ID is a valid real backend patient ID.
 * Real IDs are UUIDs or non-demo database IDs generated by the backend.
 */
export function isRealPatientId(id?: string | null): id is string {
  if (!id || typeof id !== 'string') return false;
  const trimmed = id.trim();
  if (!trimmed) return false;
  if (isDemoId(trimmed)) return false;

  // Legit UUID or valid non-demo string ID
  return UUID_REGEX.test(trimmed) || (!trimmed.startsWith('patient-') && !trimmed.startsWith('demo-') && trimmed.length >= 6);
}

/**
 * Checks whether the application or patient is currently in demo mode.
 */
export function isDemoMode(patientId?: string | null): boolean {
  return !isRealPatientId(patientId);
}

/**
 * Global switch allowing demo fallback to be toggled off entirely in production environments.
 */
export const DEMO_FALLBACK_ENABLED = true;

// =============================================================================
// Typed Demo Data Accessors
// =============================================================================

export function getDemoPatient(id?: string): PatientProfile {
  if (id) {
    const found = DEMO_PATIENTS.find((p) => p.id === id);
    if (found) return JSON.parse(JSON.stringify(found));
  }
  return JSON.parse(JSON.stringify(INITIAL_PATIENT));
}

export function getDemoPatients(): PatientProfile[] {
  return JSON.parse(JSON.stringify(DEMO_PATIENTS));
}

export function getDemoCaretaker(): CaretakerProfile {
  return JSON.parse(JSON.stringify(INITIAL_CARETAKER));
}

export function getDemoMedications(): Medication[] {
  return JSON.parse(JSON.stringify(INITIAL_MEDICATIONS));
}

export function getDemoFamilyMembers(): FamilyMember[] {
  return JSON.parse(JSON.stringify(INITIAL_FAMILY_MEMBERS));
}

export function getDemoAppointments(): Appointment[] {
  return JSON.parse(JSON.stringify(INITIAL_APPOINTMENTS));
}

export function getDemoCognitiveMetrics(patientId?: string): CognitiveMetrics {
  if (patientId && DEMO_COGNITIVE_METRICS[patientId]) {
    return JSON.parse(JSON.stringify(DEMO_COGNITIVE_METRICS[patientId]));
  }
  return JSON.parse(JSON.stringify(INITIAL_COGNITIVE_METRICS));
}

export function getDemoGameHistory(patientId?: string): GameScoreResult[] {
  if (patientId && DEMO_PATIENT_GAME_HISTORY[patientId]) {
    return JSON.parse(JSON.stringify(DEMO_PATIENT_GAME_HISTORY[patientId]));
  }
  return JSON.parse(JSON.stringify(INITIAL_GAME_HISTORY));
}

export function getDemoAIInsights() {
  return JSON.parse(JSON.stringify(INITIAL_AI_INSIGHTS));
}

export function getDemoWeeklyReport() {
  return JSON.parse(JSON.stringify(WEEKLY_ANALYTICS_DATA));
}

export function getDemoAlerts(): AlertItem[] {
  return JSON.parse(JSON.stringify(INITIAL_ALERTS));
}

export function getDemoStories(): FamilyStory[] {
  return JSON.parse(JSON.stringify(INITIAL_STORIES));
}

export function getDemoHydrationSettings(): HydrationSettings {
  return JSON.parse(JSON.stringify(INITIAL_HYDRATION_SETTINGS));
}

export { CORE_GAMES, DEMO_DATA_DISCLAIMER };
