from datetime import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, ConfigDict


class AIStatusResponse(BaseModel):
    available: bool = Field(..., description="Whether Gemini AI services are configured and operational")
    status: str = Field(..., description="Detailed status string (e.g. 'operational', 'offline_mode', 'api_key_missing')")
    model: str = Field(..., description="Active Gemini text model")
    voice_model: str = Field(..., description="Active Gemini Live voice model")
    voice_enabled: bool = Field(..., description="Whether Gemini Live voice streaming is enabled")
    supported_languages: List[str] = Field(default_factory=lambda: ["en", "hi", "as", "bn", "mni"], description="Supported patient interaction languages")
    message: Optional[str] = Field(None, description="Human-friendly status explanation")


class VoiceSessionCreateRequest(BaseModel):
    patient_id: str = Field(..., description="Target patient UUID")
    preferred_language: Optional[str] = Field(None, description="Language code e.g. 'en', 'hi', 'as'")
    voice_name: Optional[str] = Field(None, description="Preferred voice tone e.g. 'Puck', 'Charon', 'Kore', 'Fenrir', 'Aoede'")


class VoiceSessionResponse(BaseModel):
    session_id: str = Field(..., description="Unique voice session identifier")
    patient_id: str = Field(..., description="Target patient UUID")
    websocket_url: str = Field(..., description="WebSocket URI for Gemini Live audio streaming")
    ephemeral_token: str = Field(..., description="Short-lived client-safe session authorization token (never leaks GEMINI_API_KEY)")
    expires_in: int = Field(3600, description="Token lifetime in seconds")
    language: str = Field(..., description="Resolved interaction language")
    model: str = Field(..., description="Gemini voice model in use")
    system_instruction: str = Field(..., description="System instruction active for the voice assistant")


class VoiceTokenRequest(BaseModel):
    session_id: str = Field(..., description="Voice session ID")
    patient_id: str = Field(..., description="Patient UUID")


class VoiceTokenResponse(BaseModel):
    token: str = Field(..., description="Client-safe short-lived session token")
    token_type: str = Field("Bearer", description="Token authentication scheme")
    expires_in: int = Field(3600, description="Token expiry in seconds")
    model: str = Field(..., description="Assigned voice model")


class ChatMessage(BaseModel):
    role: str = Field(..., description="'user' | 'assistant' | 'system'")
    content: str = Field(..., description="Message text content")
    timestamp: Optional[datetime] = Field(None, description="Message timestamp")


class AIChatRequest(BaseModel):
    patient_id: str = Field(..., description="Patient UUID")
    message: str = Field(..., description="User query or voice transcript")
    conversation_history: Optional[List[ChatMessage]] = Field(default_factory=list, description="Recent conversation turns")
    language: Optional[str] = Field(None, description="Language override (defaults to patient's preferred language)")


class AIChatResponse(BaseModel):
    reply: str = Field(..., description="Assistant response text")
    language: str = Field(..., description="Response language")
    tool_calls_executed: List[str] = Field(default_factory=list, description="Backend database tools invoked to answer")
    available: bool = Field(True, description="Whether response was generated by Gemini or fallback assistant")
    model: str = Field(..., description="AI model used")


class AIInsightGenerateRequest(BaseModel):
    force_refresh: bool = Field(False, description="Whether to recompute fresh insights even if recent ones exist")
    timeframe: str = Field("week", description="Analytics timeframe ('week', 'month')")


class AIInsightResponse(BaseModel):
    id: str = Field(..., description="Insight UUID")
    patient_id: str = Field(..., description="Patient UUID")
    summary: str = Field(..., description="Holistic, non-diagnostic caregiver summary")
    positive_observations: List[str] = Field(default_factory=list, description="Strengths and positive activity engagement trends")
    areas_to_watch: List[str] = Field(default_factory=list, description="Activity domains with higher error rate or lower participation")
    activity_observations: List[str] = Field(default_factory=list, description="Specific observations regarding memory, attention, or pattern exercises")
    suggested_actions: List[str] = Field(default_factory=list, description="Supportive, non-medical recommendations for caregivers")
    confidence: str = Field("moderate", description="Confidence level: 'low' | 'moderate' | 'high'")
    model: str = Field(..., description="Model identifier used to produce insight")
    source_metrics_version: str = Field("v1.0", description="Version of source metrics schema")
    generated_at: datetime = Field(..., description="Timestamp of generation")

    model_config = ConfigDict(from_attributes=True)
